
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sharding_db?useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
